development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: deepak.cvr@gmail.com
  :password: stelex3031
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: deepak.cvr@gmail.com
  :password: stelex3031
  :enable_starttls_auto: true